import '@/public/styles/global.css'
export const metadata = {
  title: 'Torpedo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="select-none" lang="en">
      <body>{children}</body>
    </html>
  )
}
